name: Deploy Dockerized Node.js Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

       - name: Copy .env file to remote server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .env
          target: ~/secrets_node/.env

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerized_service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/dockerized_service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dockerized_service:latest
            docker stop dockerized_service || true
            docker rm dockerized_service || true
            docker run -d --name dockerized_service -p 3000:3000 --env-file ~/secrets_node/.env ${{ secrets.DOCKER_USERNAME }}/dockerized_service:latest
